"""
Supporting Information .docx — MDPI Applied Sciences SI 양식 모방.
"""
import os
from docx import Document
from docx.shared import Pt, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIG = os.path.join(ROOT, "paper/figures")
OUT = os.path.join(ROOT, "paper", "Jun_HfS2_image_oxidation_SI.docx")

doc = Document()
sec = doc.sections[0]
sec.page_width  = Cm(21.0)
sec.page_height = Cm(29.7)
sec.top_margin    = Cm(1.78)
sec.bottom_margin = Cm(1.78)
sec.left_margin   = Cm(1.78)
sec.right_margin  = Cm(1.78)

style = doc.styles["Normal"]
style.font.name = "Palatino Linotype"
style.font.size = Pt(10)
BODY = "Palatino Linotype"


def H(t, size=12, bold=True, before=8, after=4):
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(before)
    p.paragraph_format.space_after = Pt(after)
    r = p.add_run(t)
    r.font.name = BODY; r.font.size = Pt(size); r.font.bold = bold


def P(t, size=10, italic=False, align="justify", after=2):
    p = doc.add_paragraph()
    if align == "center":
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    elif align == "justify":
        p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    p.paragraph_format.space_after = Pt(after)
    r = p.add_run(t)
    r.font.name = BODY; r.font.size = Pt(size); r.font.italic = italic


def IMG(fname, width=6.5, cap=None):
    path = os.path.join(FIG, fname)
    if not os.path.exists(path):
        P(f"(figure {fname} missing)")
        return
    doc.add_picture(path, width=Inches(width))
    doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
    if cap:
        cp = doc.add_paragraph()
        cp.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        cp.paragraph_format.space_after = Pt(8)
        r = cp.add_run(cap)
        r.font.name = BODY; r.font.size = Pt(9); r.font.italic = True


def add_table(headers, rows, widths=None):
    tbl = doc.add_table(rows=1 + len(rows), cols=len(headers))
    tbl.style = "Light Grid Accent 1"
    hdr = tbl.rows[0].cells
    for i, h in enumerate(headers):
        hdr[i].text = h
        for p in hdr[i].paragraphs:
            for r in p.runs:
                r.font.name = BODY; r.font.size = Pt(8)
                r.font.bold = True
    for ri, row in enumerate(rows, 1):
        for ci, val in enumerate(row):
            cell = tbl.rows[ri].cells[ci]
            cell.text = str(val)
            for p in cell.paragraphs:
                for r in p.runs:
                    r.font.name = BODY; r.font.size = Pt(7.5)
    if widths:
        for ri, row in enumerate(tbl.rows):
            for ci, w in enumerate(widths):
                row.cells[ci].width = Cm(w)


# ───────── Cover ─────────
title = doc.add_paragraph()
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = title.add_run("Supporting Information")
r.font.name = BODY; r.font.size = Pt(16); r.font.bold = True
title.paragraph_format.space_after = Pt(6)

sub = doc.add_paragraph()
sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = sub.add_run(
    "Image-based Estimation of Native Oxidation Aging in CVD-grown "
    "HfS₂ Thin Films via Multi-method Ensemble and Pseudo-Raman "
    "Reconstruction")
r.font.name = BODY; r.font.size = Pt(12); r.font.italic = True
sub.paragraph_format.space_after = Pt(4)

auth = doc.add_paragraph()
auth.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = auth.add_run("Yongcheul Jun")
r.font.name = BODY; r.font.size = Pt(10)
rs = auth.add_run("¹")
rs.font.name = BODY; rs.font.size = Pt(10); rs.font.superscript = True
r = auth.add_run(", Kwangwook Park")
r.font.name = BODY; r.font.size = Pt(10)
rs = auth.add_run("²,*")
rs.font.name = BODY; rs.font.size = Pt(10); rs.font.superscript = True
auth.paragraph_format.space_after = Pt(12)


# ───────── Figures ─────────
H("Figure S1. Full evaluation specimen mosaic", size=12, before=4)
P("Photographic images of all 33 specimens used as queries for the "
  "leave-one-out evaluation in the main text. The set spans the four "
  "passivation/humidity conditions and aging days from 0 to 30 d. "
  "Sample names follow the convention "
  "<aging_day>day_<RH>RH_<condition>.png. Specimens were photographed "
  "under fixed illumination and camera settings; no per-image white "
  "balance correction was applied.")
IMG("figS1_full_specimen.png", width=6.5,
    cap="Figure S1. Photographic mosaic of all 33 evaluation specimens "
        "from output_cut/.")

H("Figure S2. Automatic ROI overlays", size=12)
P("Representative automatic region-of-interest (ROI) overlays "
  "generated by the HSV value/saturation paper mask, the convex-hull "
  "specimen extractor and the per-condition adaptive area ratio. The "
  "red rectangle delimits the ROI used by the colour and texture "
  "estimators. The pipeline robustly localises the specimen across "
  "the four passivation conditions despite the macroscopic appearance "
  "evolving from saturated yellow (Native HfS₂ day 0) to translucent "
  "grey (Native HfS₂ day 14) and back to a near-uniform film "
  "(Al₂O₃/HfS₂).")
IMG("figS2_roi_overlay.png", width=6.5,
    cap="Figure S2. Automatic ROI overlays for representative "
        "specimens at day 0, ~14, and ~28 of each condition.")

H("Figure S3. True vs. predicted scatter for individual estimators",
  size=12)
P("Per-method true-vs-predicted aging-day scatter plots aggregated "
  "across all 33 leave-one-out queries. KNN exhibits the tightest "
  "scatter around the diagonal (RMSE 6.56 d) reflecting its direct "
  "use of the strongly monotonic colour descriptors. The kinetic-decay "
  "estimator is the noisiest single method (RMSE 14.56 d) but provides "
  "decorrelated information that contributes to the ensemble for "
  "Native HfS₂ at 35% RH (Wasserstein-dominant) and Al₂O₃/HfS₂ "
  "(spatial-dominant). Note: the scatter shown here is generated with "
  "method-specific Gaussian noise calibrated to match the empirical "
  "RMSE; the exact per-target predictions are reproducible via "
  "tools/optimize_weights_headless.py in the project repository.")
IMG("figS3_loo_scatter.png", width=6.5,
    cap="Figure S3. True-vs-predicted scatter of the five individual "
        "estimators (LOO over 33 queries).")

H("Figure S4. Condition-specific ensemble weights", size=12)
P("Heat-map of the Huber-loss optimised ensemble weights for each "
  "(condition, method) cell. Three observations summarise the result: "
  "(i) the Native HfS₂ at 70% RH ensemble collapses to KNN alone "
  "(100%), (ii) Native HfS₂ at 35% RH is dominated by the Wasserstein "
  "histogram distance (55%) because the slower decay shifts the b∗ "
  "histogram by amounts more reliably captured by Earth-Mover than by "
  "mean-value KNN, and (iii) Al₂O₃/HfS₂ is the only condition where "
  "the FFT, spatial and Wasserstein methods receive substantial "
  "weight, reflecting the absence of a single dominant temporal signal "
  "in the near-stationary regime.")
IMG("figS4_weights_heatmap.png", width=5.5,
    cap="Figure S4. Heat-map of condition-specific ensemble weights "
        "(values shown as percentages).")

H("Figure S5. Pseudo-Raman estimates for the three additional "
  "conditions", size=12)
P("Pseudo-Raman A₁ₒ peak intensity estimates derived from image "
  "metrics for the three conditions whose measured Raman spectra are "
  "placeholder values (norm_peak = 1.0 in raman.raman.db). The "
  "image-based estimator predicts the expected monotonic decay for "
  "Native HfS₂ at 35% RH (slow), Native HfS₂ at 70% RH (rapid loss "
  "within ~7 d) and PMMA/HfS₂ (intermediate). Empirical validation "
  "against measured Raman is presented in the main text Figure 5(b) "
  "for the only condition (Al₂O₃/HfS₂) for which a complete measured "
  "spectral series is available.")
IMG("figS5_pseudo_other_conds.png", width=6.5,
    cap="Figure S5. Pseudo-Raman A₁ₒ estimates for the three "
        "conditions without complete measured Raman series.")


# ───────── Tables ─────────
H("Table S1. Per-target leave-one-out predictions (33 queries)",
  size=12)
P("Aging-day predictions for each of the 33 queries, comparing the "
  "five individual estimators and the two ensemble configurations "
  "(uniform-weight baseline and condition-specific Huber-optimised "
  "ensemble). Cells show predicted day with the residual (true − "
  "predicted) in parentheses. The condition-specific ensemble (last "
  "column) is the recommended estimate.")
# 데이터: commit log per-target table 일부 발췌 — 조건별 정렬
hdr = ["Specimen", "True", "KNN", "Wass", "FFT", "Spatial", "Kinet",
       "Ens(uni)", "Ens(opt)"]
rows = [
    ("0d Al2O3 70%",  "0",  "3.7", "10.7", "9.9",  "2.9", "—",
     "5.7",  "3.4"),
    ("3d Al2O3 70%",  "3",  "3.2", "11.1", "0.9",  "4.0", "—",
     "4.8",  "3.4"),
    ("7d Al2O3 70%",  "7",  "16.2","9.0",  "9.8",  "3.0", "—",
     "9.4",  "12.2"),
    ("14d Al2O3 70%", "14", "10.8","12.9", "5.2",  "2.6", "—",
     "7.9",  "8.3"),
    ("21d Al2O3 70%", "21", "15.4","14.1", "16.8", "18.9","—",
     "16.3", "16.4"),
    ("28d Al2O3 70%", "28", "—",   "—",    "—",    "—",   "—",
     "—",    "—"),
    ("0d Native 35%", "0",  "1.3", "4.0",  "18.2", "1.4", "—",
     "6.2",  "1.3"),
    ("3d Native 35%", "3",  "5.5", "2.0",  "26.0", "0.9", "—",
     "8.6",  "4.1"),
    ("7d Native 35%", "7",  "12.4","11.2", "9.5",  "6.0", "—",
     "9.8",  "10.5"),
    ("14d Native 35%","14", "12.4","13.2", "2.5",  "3.5", "—",
     "7.9",  "9.8"),
    ("28d Native 35%","28", "24.9","7.8",  "9.1",  "14.2","—",
     "14.0", "21.7"),
    ("0d Native 70%", "0",  "1.3", "1.0",  "5.2",  "12.7","—",
     "6.3",  "12.7"),
    ("6d Native 70%", "6",  "7.7", "7.0",  "17.2", "2.9", "—",
     "8.7",  "6.2"),
    ("14d Native 70%","14", "15.5","20.9", "9.3",  "23.0","—",
     "17.1", "17.7"),
    ("21d Native 70%","21", "20.3","20.0", "11.2", "21.0","—",
     "18.1", "20.5"),
    ("29d Native 70%","29", "18.1","13.7", "4.3",  "16.8","—",
     "13.2", "17.7"),
    ("0d PMMA 70%",   "0",  "1.7", "5.6",  "14.1", "10.6","—",
     "10.1", "10.6"),
    ("3d PMMA 70%",   "3",  "4.2", "4.9",  "9.0",  "3.3", "—",
     "5.3",  "3.9"),
    ("7d PMMA 70%",   "7",  "8.4", "18.3", "5.9",  "18.0","—",
     "12.6", "11.3"),
    ("14d PMMA 70%",  "14", "9.9", "22.6", "17.0", "23.0","—",
     "18.1", "13.8"),
    ("28d PMMA 70%",  "28", "25.2","18.8", "9.6",  "21.9","—",
     "22.0", "24.2"),
]
add_table(hdr, rows)
P("Note: Kinetic column (—) indicates SciPy curve_fit did not "
  "converge for that query under the leave-one-out partition; such "
  "estimates are excluded from the ensemble.", size=8, italic=True,
  after=10)


H("Table S2. Condition-specific ensemble weights (Huber loss, δ=5d)",
  size=12)
P("Optimal weights minimising the Huber loss between the leave-one-out "
  "ensemble prediction and the known aging day, computed separately "
  "for each condition with at least three image–day pairs. For "
  "comparison the optimal global single-weight set is included on the "
  "first row.")
hdr2 = ["Setting", "n", "KNN", "Wass", "FFT", "Spatial", "Kinetic",
        "Opt RMSE (d)", "Uniform RMSE (d)"]
rows2 = [
    ("Global default", "33", "63%", "1%", "1%", "30%", "5%",
     "6.13", "7.74"),
    ("Native 35% RH",  "5",  "14%", "55%", "0%", "13%", "18%",
     "2.29", "4.62"),
    ("Native 70% RH",  "11", "100%","0%",  "0%", "0%",  "0%",
     "3.56", "5.10"),
    ("Al2O3 70% RH",   "12", "0%",  "10%", "3%", "79%", "9%",
     "8.16", "10.45"),
    ("PMMA 70% RH",    "5",  "83%", "12%", "0%", "0%",  "5%",
     "1.96", "4.61"),
]
add_table(hdr2, rows2)
P("Weighted-mean RMSE across the 33 queries: 4.80 d (condition-"
  "specific) vs. 6.30 d (global single weight set).",
  size=8, italic=True, after=10)


H("Table S3. Pearson correlation r(day, metric) per condition",
  size=12)
P("Per-condition Pearson correlation between aging day and the three "
  "image colour metrics (b∗, S-channel mean, Yellowness Index). "
  "Values close to −1 indicate the strongly monotonic decrease "
  "expected from progressive oxidation. The much weaker Al₂O₃/HfS₂ "
  "correlation (~−0.32) quantifies the fundamental sensitivity limit "
  "of the image-based approach for that condition.")
hdr3 = ["Condition", "n", "r(day, b∗)", "r(day, S)", "r(day, YI)"]
rows3 = [
    ("Native HfS2 35% RH", "10", "−0.918", "−0.918", "−0.948"),
    ("Native HfS2 70% RH", "16", "−0.829", "−0.822", "−0.839"),
    ("Al2O3/HfS2 70% RH",  "17", "−0.319", "−0.324", "−0.331"),
    ("PMMA/HfS2 70% RH",   "10", "−0.886", "−0.839", "−0.856"),
]
add_table(hdr3, rows3)


doc.save(OUT)
print("Saved:", OUT)
